import type { TopicConfig } from '../types'

const SHARED_TEMPLATE_IMAGES: [string, string, string] = [
  'https://res.cloudinary.com/dymmqtqyg/image/upload/v1775189927/epl-post-challenge_1_byvuse.jpg',
  'https://res.cloudinary.com/dymmqtqyg/image/upload/v1775199810/epl-post-debate_sqjs6z.jpg',
  'https://res.cloudinary.com/dymmqtqyg/image/upload/v1775199812/epl-post-quiz_c1piip.jpg',
]

export const TOPIC_CONFIGS: Record<string, TopicConfig> = {
  epl: {
    id: 'epl',
    label: 'EPL',
    trendingTopicsWebhookEnvVar: 'VITE_ENGAGEMENT_TRENDING_TOPICS_WEBHOOK_URL',
    webhookEnvVar: 'VITE_EPL_IDEA_GENERATION_WEBHOOK_URL',
    uploadPresetEnvVar: 'VITE_CLOUDINARY_EPL_UPLOAD_PRESET',
    templateImages: SHARED_TEMPLATE_IMAGES,
    loadingSteps: ['Scanning latest EPL news', 'Curating top stories', 'Generating 5 post ideas'],
    loadingQuotes: ['VAR checking the vibes...', 'Consulting the dugout...', 'Asking the fans...', 'Reading the match report...'],
    downloadPrefix: 'epl-post',
  },
  ucl: {
    id: 'ucl',
    label: 'Champions League',
    trendingTopicsWebhookEnvVar: 'VITE_UCL_TRENDING_TOPICS_WEBHOOK_URL',
    webhookEnvVar: 'VITE_UCL_IDEA_GENERATION_WEBHOOK_URL',
    uploadPresetEnvVar: 'VITE_CLOUDINARY_UCL_UPLOAD_PRESET',
    templateImages: SHARED_TEMPLATE_IMAGES,
    loadingSteps: ['Scanning latest UCL news', 'Curating top stories', 'Generating 5 post ideas'],
    loadingQuotes: ['Checking VAR in UEFA HQ...', 'Consulting the dugout...', 'Asking the ultras...', 'Reading the match report...'],
    downloadPrefix: 'ucl-post',
  },
  badminton: {
    id: 'badminton',
    label: 'Badminton',
    trendingTopicsWebhookEnvVar: 'VITE_BADMINTON_FETCH_IDEAS_WEBHOOK_URL',
    webhookEnvVar: 'VITE_BADMINTON_POSTS_WEBHOOK_URL',
    uploadPresetEnvVar: 'VITE_CLOUDINARY_BADMINTON_UPLOAD_PRESET',
    templateImages: SHARED_TEMPLATE_IMAGES,
    loadingSteps: ['Searching latest badminton news', 'Analyzing the rallies', 'Generating post ideas'],
    loadingQuotes: ['Checking the shuttlecock trajectory...', 'Consulting the badminton federation...', 'Reading the tournament report...', 'Analyzing the smash technique...'],
    loadingIcon: '🏸',
    downloadPrefix: 'badminton-post',
    useCanvas: true,
    photosWebhookEnvVar: 'VITE_BADMINTON_PHOTOS_WEBHOOK_URL',
    photosCacheKey: 'Badminton',
    headlineLimit: 50,
    subtitleLimit: 200,
    captionLimit: 550,
  },
  motogp: {
    id: 'motogp',
    label: 'MotoGP',
    trendingTopicsWebhookEnvVar: 'VITE_MOTOGP_FETCH_IDEAS_WEBHOOK_URL',
    webhookEnvVar: 'VITE_MOTOGP_POSTS_WEBHOOK_URL',
    uploadPresetEnvVar: 'VITE_CLOUDINARY_MOTOGP_UPLOAD_PRESET',
    templateImages: SHARED_TEMPLATE_IMAGES,
    loadingSteps: ['Searching latest MotoGP news', 'Analyzing the race results', 'Generating post ideas'],
    loadingQuotes: ['Checking the lap times...', 'Consulting the pit lane...', 'Reading the race report...', 'Analyzing the championship standings...'],
    loadingIcon: '🏍️',
    downloadPrefix: 'motogp-post',
    useCanvas: true,
    photosWebhookEnvVar: 'VITE_MOTOGP_PHOTOS_WEBHOOK_URL',
    photosCacheKey: 'MotoGP',
    headlineLimit: 50,
    subtitleLimit: 200,
    captionLimit: 550,
  },
}
